export const jobs = [
  {
    id: 1,
    title: "Frontend Developer",
    company: "TechNova Ltd.",
    location: "Dhaka, Bangladesh",
    type: "Full Time",
    mode: "Remote",
    experience: "Mid Level",
    salary: "৳50K - ৳80K",
    category: "Technology",
    posted: "2 days ago",
    description:
      "We are looking for a skilled Frontend Developer to build modern and responsive web applications.",
    skills: ["React", "JavaScript", "Tailwind CSS"],
  },
  {
    id: 2,
    title: "UI/UX Designer",
    company: "Creative Studio",
    location: "Dhaka, Bangladesh",
    type: "Full Time",
    mode: "Hybrid",
    experience: "Mid Level",
    salary: "৳40K - ৳65K",
    category: "Design",
    posted: "3 days ago",
    description:
      "Join our creative team and design beautiful digital experiences for our growing products.",
    skills: ["Figma", "UI Design", "UX Research"],
  },
  {
    id: 3,
    title: "Digital Marketing Executive",
    company: "GrowthHub",
    location: "Chattogram, Bangladesh",
    type: "Full Time",
    mode: "On-site",
    experience: "Entry Level",
    salary: "৳25K - ৳40K",
    category: "Marketing",
    posted: "5 days ago",
    description:
      "Help us grow our digital presence through creative campaigns and effective marketing strategies.",
    skills: ["SEO", "Social Media", "Google Ads"],
  },
  {
    id: 4,
    title: "Backend Developer",
    company: "CodeCraft",
    location: "Remote",
    type: "Contract",
    mode: "Remote",
    experience: "Senior Level",
    salary: "৳80K - ৳120K",
    category: "Technology",
    posted: "1 week ago",
    description:
      "Build scalable backend systems and APIs for high-performance web applications.",
    skills: ["Node.js", "Express", "MongoDB"],
  },
  {
    id: 5,
    title: "HR Executive",
    company: "PeopleFirst",
    location: "Dhaka, Bangladesh",
    type: "Full Time",
    mode: "On-site",
    experience: "Mid Level",
    salary: "৳35K - ৳55K",
    category: "Human Resources",
    posted: "1 week ago",
    description:
      "Manage recruitment, employee relations, and HR operations in a fast-growing organization.",
    skills: ["Recruitment", "HR Management", "Communication"],
  },
  {
    id: 6,
    title: "React Intern",
    company: "DevPoint",
    location: "Dhaka, Bangladesh",
    type: "Internship",
    mode: "Hybrid",
    experience: "Entry Level",
    salary: "৳10K - ৳15K",
    category: "Technology",
    posted: "2 weeks ago",
    description:
      "Start your development career by working with experienced developers on real-world projects.",
    skills: ["React", "JavaScript", "Git"],
  },
];
